//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouncilGamingClub
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerInfo
    {
        public int ID { get; set; }
        public string UniqueID { get; set; }
        public string CustomerFname { get; set; }
        public string CustomerLname { get; set; }
        public string Address { get; set; }
    }
}
