//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouncilGamingClub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID { get; set; }
        public string Product_Name { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public int Cust_ID { get; set; }
    
        public virtual CustomerInfo CustomerInfo { get; set; }
    }
}
