//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouncilGamingClub
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierTable
    {
        public int ID { get; set; }
        public string SupplierName { get; set; }
        public string SupplierID { get; set; }
        public string Address { get; set; }
    
        public virtual InventoryTable InventoryTable { get; set; }
    }
}
